// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh2B2761-O7RJUbD4RvV-vkFrUAzRcgUI',
    appId: '1:874318126804:web:c0bd26041bb4c950902541',
    messagingSenderId: '874318126804',
    projectId: 'berkatjayaweb',
    authDomain: 'berkatjayaweb.firebaseapp.com',
    storageBucket: 'berkatjayaweb.firebasestorage.app',
    measurementId: 'G-MX93ZLR00R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj49CwAA2Fd_9O375kccCyJKrl7zeVP9Q',
    appId: '1:874318126804:android:41d44949b7280f6c902541',
    messagingSenderId: '874318126804',
    projectId: 'berkatjayaweb',
    storageBucket: 'berkatjayaweb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA6lxZgqbiHbEaCyrDFGJ72TJJPBjvp3c',
    appId: '1:874318126804:ios:6fcf026a9b79995c902541',
    messagingSenderId: '874318126804',
    projectId: 'berkatjayaweb',
    storageBucket: 'berkatjayaweb.firebasestorage.app',
    iosBundleId: 'com.example.berkatjayaWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA6lxZgqbiHbEaCyrDFGJ72TJJPBjvp3c',
    appId: '1:874318126804:ios:6fcf026a9b79995c902541',
    messagingSenderId: '874318126804',
    projectId: 'berkatjayaweb',
    storageBucket: 'berkatjayaweb.firebasestorage.app',
    iosBundleId: 'com.example.berkatjayaWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh2B2761-O7RJUbD4RvV-vkFrUAzRcgUI',
    appId: '1:874318126804:web:f8b1e075319d5746902541',
    messagingSenderId: '874318126804',
    projectId: 'berkatjayaweb',
    authDomain: 'berkatjayaweb.firebaseapp.com',
    storageBucket: 'berkatjayaweb.firebasestorage.app',
    measurementId: 'G-YFW20SM6HJ',
  );
}
